name: Copy website files to gh-pages

on:
  push:
    branches:
      - master

jobs:
  copy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate diff
      - name: Git Configuration
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Copy website files to gh-pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages # Checkout gh-pages or create if it doesn't exist
          rsync -av --delete src/main/java/io/github/keebrunner/blog/blog/ ./blog/
          rsync -av --delete src/main/java/io/github/keebrunner/blog/css/ ./css/
          rsync -av --delete src/main/java/io/github/keebrunner/blog/img/ ./img/
          rsync -av --delete src/main/java/io/github/keebrunner/blog/js/ ./js/
          rsync -av --delete src/main/java/io/github/keebrunner/blog/index.html ./
          rsync -av --delete src/main/java/io/github/keebrunner/blog/blog.html ./
          rsync -av --delete src/main/java/io/github/keebrunner/blog/java.html ./
          rsync -av --delete src/main/java/io/github/keebrunner/blog/metrics.html ./
          rsync -av --delete src/main/java/io/github/keebrunner/blog/post.html ./
          git add .
          git commit -m "Update website files in gh-pages" || echo "No changes to commit"
          git push origin gh-pages