name: Copy site

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Configuration
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Copy site
        run: |
          
          cp -r src/main/java/io/github/keebrunner/blog/blog .
          cp -r src/main/java/io/github/keebrunner/blog/css .
          cp -r src/main/java/io/github/keebrunner/blog/img .
          cp -r src/main/java/io/github/keebrunner/blog/js .
          cp src/main/java/io/github/keebrunner/blog/index.html .
          cp src/main/java/io/github/keebrunner/blog/blog.html .
          cp src/main/java/io/github/keebrunner/blog/java.html .
          cp src/main/java/io/github/keebrunner/blog/metrics.html .
          cp src/main/java/io/github/keebrunner/blog/post.html .
          git add .
          
          git commit -m "Update website files"
          git push -f origin master
