name: Copy output.html in gh-pages

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git Configuration
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Copy output.html in gh-pages
        run: |
          
          git checkout --orphan gh-pages
          git rm --cached -r .
          cp src/main/java/io/github/keebrunner/blog/output.html .
          git add output.html
          git clean -fd -e output.html
          git commit -m "Update output.html in gh-pages"
          git push -f origin gh-pages
