name: Copy output.html to gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Copy output.html to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout --orphan gh-pages
          # Delete any existing files in the gh-pages branch
          rm -rf *
          cp src/main/java/io/github/keebrunner/blog/output.html .
          git add output.html
          git commit -m "Update output.html in gh-pages"
          git push origin gh-pages