name: Copy output.html to gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy output.html to gh-pages
        run: |
          cp src/main/java/io/github/keebrunner/blog/output.html gh-pages/
          git commit -m "Update output.html in gh-pages"
          git push origin gh-pages